logging:
  level_name: "DEBUG"

# LLM settings
llm: "openai/gpt-4o"
embed_model: "openai/text-embedding-3-large"
openai_api_key: ""
# common app settings
title: "Documents API"
description: ""
version: "0.1.0"

host: "0.0.0.0"
port: 8080