logging:
  level_name: "DEBUG"

title: "Catalog Service"
description: ""
version: "0.1.0"

host: "127.0.0.1"
port: 9000
reload: false
api_prefix: "/v1"
cors_origins: ["*"]
service_name: ""
metadata:
  owner: "catalog-team"
